dist: focal
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libchromaprint-dev
      - libflac++-dev
      - libfuse-dev
      - libid3tag0-dev
      - libmp3lame-dev
      - libsox-dev
      - libvorbis-dev
      - pandoc
      - python3-mutagen
script: ./autogen.sh && ./configure && make && make check && make staticcheck
