# Basic Docker Compose file for mp3fs
version: '3'
services:
    mp3fs:
        image: khenriks/mp3fs
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        volumes:
            - ${MUSICDIR}:/music:ro
            - ${MP3DIR}:/mnt:shared
        command: ${MP3FS_FLAGS}
